INSERT INTO doctors_of_polyclinics (polyclinic_id, doctor_id) VALUES (1, 10)
INSERT INTO doctors_of_polyclinics (polyclinic_id, doctor_id) VALUES (2, 4)
INSERT INTO doctors_of_polyclinics (polyclinic_id, doctor_id) VALUES (3, 1)
INSERT INTO doctors_of_polyclinics (polyclinic_id, doctor_id) VALUES (2, 5)
INSERT INTO doctors_of_polyclinics (polyclinic_id, doctor_id) VALUES (1, 12)
