INSERT INTO doctors_of_hospitals (hospital_id, doctor_id) VALUES (1, 9)
INSERT INTO doctors_of_hospitals (hospital_id, doctor_id) VALUES (2, 2)
INSERT INTO doctors_of_hospitals (hospital_id, doctor_id) VALUES (3, 7)
INSERT INTO doctors_of_hospitals (hospital_id, doctor_id) VALUES (4, 4)
INSERT INTO doctors_of_hospitals (hospital_id, doctor_id) VALUES (5, 6)
INSERT INTO doctors_of_hospitals (hospital_id, doctor_id) VALUES (3, 1)
INSERT INTO doctors_of_hospitals (hospital_id, doctor_id) VALUES (2, 9)