INSERT INTO doctors VALUES (1, 'Петров', 'Виктор','Сергеевич', 4, 1, 0, 1, 0,5)
INSERT INTO doctors VALUES (2, 'Снегирева', 'Алена','Павловна', 3, 0, 1, 0, 1, 7)
INSERT INTO doctors VALUES (3, 'Пелешко', 'Кристина','Николаевна', 6, 0, 0, 0, 0, 4)
INSERT INTO doctors VALUES (4, 'Могребникова', 'Мария','Николаевна', 7, 0, 1, 0, 1, 2)
INSERT INTO doctors VALUES (5, 'Крюкова', 'Ольга','Петровна', 1, 1, 0, 1, 0, 12)
INSERT INTO doctors VALUES (6, 'Воробьев', 'Андрей','Романович', 2, 0, 0, 0, 0, 8)
INSERT INTO doctors VALUES (7, 'Тринкер', 'Борис','Давидович', 10, 1, 0, 1, 0, 11)
INSERT INTO doctors VALUES (8, 'Иванов', 'Александр','Николаевич', 2, 0, 0, 0, 0, 6)
INSERT INTO doctors VALUES (9, 'Иванов', 'Петр','Федор', 7, 1, 0, 1, 0, 12)
INSERT INTO doctors VALUES (10, 'Мухаремова', 'Татьяна','Геннадьевна', 3, 1, 0, 1, 0, 19)
INSERT INTO doctors VALUES (11, 'Аникеева', 'Елена','Трофимовна', 4, 0, 0, 0, 0, 1)
INSERT INTO doctors VALUES (12, 'Татарчуков', 'Руслан','Валентинович', 8, 0, 1, 0, 1, 4)