INSERT INTO hospitals (name, address, main_doctor_id, phone_number) VALUES ('Клиника малоинвазивной хирургии', 'ул. Погодинская, д. 1', 7, '89138945976')
INSERT INTO hospitals (name, address, main_doctor_id, phone_number) VALUES ('Центр хирургии Петровского', 'Абрикосовский пер., д. 2', 6, '89133768136')
INSERT INTO hospitals (name, address, main_doctor_id, phone_number) VALUES ('Онкологическая больница №62', 'ул. Шоссейная, д. 43', 9, '89137961345')
INSERT INTO hospitals (name, address, main_doctor_id, phone_number) VALUES ('Клиника психиатрии Корсакова', 'ул. Россолимо, д. 11', 11, '89133194657')
INSERT INTO hospitals (name, address, main_doctor_id, phone_number) VALUES ('МНОЦ МГУ им. Ломоносова', 'пр-т Ломоносовский, д. 27', 2, '89134698713')