INSERT INTO ss_of_polyclinics (polyclinic_id, ss_id) VALUES (1, 1)
INSERT INTO ss_of_polyclinics (polyclinic_id, ss_id) VALUES (2, 2)
INSERT INTO ss_of_polyclinics (polyclinic_id, ss_id) VALUES (3, 5)
INSERT INTO ss_of_polyclinics (polyclinic_id, ss_id) VALUES (1, 7)
INSERT INTO ss_of_polyclinics (polyclinic_id, ss_id) VALUES (3, 10)