CREATE USER admin IDENTIFIED BY admin DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP
GRANT connect to admin
GRANT system_administrator to admin
CREATE USER pat1 IDENTIFIED BY pat1 DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP
GRANT connect to pat1
GRANT patient to pat1
CREATE USER pat2 IDENTIFIED BY pat2 DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP
GRANT connect to pat2
GRANT patient to pat2
CREATE USER pol IDENTIFIED BY pol DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP
GRANT connect to pol
GRANT polyclinic_registry to pol
CREATE USER hosp IDENTIFIED BY hosp DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP
GRANT connect to hosp
GRANT hospital_registry to hosp