CREATE ROLE system_administrator;
GRANT ALL PRIVILEGES TO system_administrator;

CREATE ROLE patient;
GRANT SELECT ON HOSPITAL_CARD TO patient;
GRANT SELECT ON POLYCLINIC_CARD TO patient;
GRANT INSERT ON POLYCLINIC_CARD TO patient;
GRANT UPDATE ON PATIENTS TO patient;

CREATE ROLE polyclinic_registry;
GRANT INSERT ON PATIENTS TO polyclinic_registry;
GRANT UPDATE ON PATIENTS TO polyclinic_registry;
GRANT DELETE ON PATIENTS TO polyclinic_registry;
GRANT INSERT ON POLYCLINIC_CARD TO polyclinic_registry;
GRANT UPDATE ON POLYCLINIC_CARD TO polyclinic_registry;
GRANT DELETE ON POLYCLINIC_CARD TO polyclinic_registry;
GRANT INSERT ON DOCTORS_OF_POLYCLINICS TO polyclinic_registry;
GRANT UPDATE ON DOCTORS_OF_POLYCLINICS TO polyclinic_registry;
GRANT DELETE ON DOCTORS_OF_POLYCLINICS TO polyclinic_registry;
GRANT INSERT ON SS_OF_POLYCLINICS TO polyclinic_registry;
GRANT UPDATE ON SS_OF_POLYCLINICS TO polyclinic_registry;
GRANT DELETE ON SS_OF_POLYCLINICS TO polyclinic_registry;

CREATE ROLE hospital_registry;
GRANT INSERT ON HOSPITAL_CARD TO hospital_registry;
GRANT UPDATE ON HOSPITAL_CARD TO hospital_registry;
GRANT DELETE ON HOSPITAL_CARD TO hospital_registry;
GRANT INSERT ON DOCTORS_OF_HOSPITALS TO hospital_registry;
GRANT UPDATE ON DOCTORS_OF_HOSPITALS TO hospital_registry;
GRANT DELETE ON DOCTORS_OF_HOSPITALS TO hospital_registry;
GRANT INSERT ON SS_OF_HOSPITALS TO hospital_registry;
GRANT UPDATE ON SS_OF_HOSPITALS TO hospital_registry;
GRANT DELETE ON SS_OF_HOSPITALS TO hospital_registry;